### ISSUE TITLE
Campos com virgulas

### ISSUE THREAD

**Issue by lmalves** [centraldedados/codigos_postais#1]
Olá,
Ao importar o ficheiro apercebi-me que alguns campos contêm virgulas, o que no ficheiro CSV vai "partir" em mais uma coluna. Ex: linha 4745, 17812. Existem cerca de 106 casos.

Caso usem como caracter separador o ; deverá resolver o problema.

Cumprimentos,
Luís

**Comment by rlafuente** [comment]
Na última atualização (85e750f), tratámos de assegurar que os campos com vírgulas são _quoted_ (aspados?) com aspas duplas (_double quotes_, ou `"`); isto deve resolver o problema dos separadores.

Obrigado pela cotovelada!
